version: '3'
services:
  app:
    build: .
    command: npm run dev
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    tty: true
